- action: []
  alias: ''
  condition: []
  id: '1521552726448'
  trigger: []
- id: fish tank light
  alias: 鱼缸灯slot
  trigger:
  - platform: sun
    event: sunrise
  - platform: sun
    event: sunset
    offset: 02:00:00
  action:
    entity_id: switch.slot
    service_template: "{% if now().strftime(\"%H\") | int < 8 %}\n  # sunrise\n  switch.turn_on\n\
      {% else %}\n  # sunset\n  switch.turn_off\n{% endif %}\n"
- id: Aquarium heater
  alias: 鱼缸加热棒slot
  trigger:
    platform: time
    minutes: /5
    seconds: 0
  action:
    entity_id: switch._slot_3
    service_template: "{% if is_state(\"switch._slot_3\", \"off\") and states.sensor.yweather_temperature.state|int\
      \ < 22  %}\n  switch.turn_on\n{%-elif is_state(\"switch._slot_3\", \"on\") %}\n\
      \  switch.turn_off\n{% endif %}\n"
- id: Aquarium water circulation
  alias: 鱼缸水循环slot
  trigger:
    platform: time
    minutes: /30
    seconds: 0
  action:
    entity_id: switch._slot
    service_template: "{% if is_state(\"switch._slot\", \"off\") %}\n  switch.turn_on\n\
      {%-elif is_state(\"switch._slot\", \"on\") %}\n  switch.turn_off\n{% endif %}\n"
