- action:
  - service: cover.close_cover_tilt
  alias: test
  condition:
  - condition: state
    entity_id: group.all_devices
    state: '1'
  id: '1521552726448'
  trigger:
  - entity_id: automation.fish_tank_light_on
    from: '1'
    platform: state
    to: '2'

# 触发条件：日落日出
# 动作：日出开日落后2小时关
- id: 'fish tank light'
  alias: 鱼缸灯slot
  trigger:
    - platform: sun
      event: sunrise
    - platform: sun
      event: sunset
      offset: '02:00:00'
  action:
    entity_id: switch.slot
    service_template: >
      {% if now().strftime("%H") | int < 8 %}
        # sunrise
        switch.turn_on
      {% else %}
        # sunset
        switch.turn_off
      {% endif %}

# 触发条件：每小时触发一次
# 动作：温度低于22度开否则关
- id: 'Aquarium heater'
  alias: 鱼缸加热棒slot
  trigger:
    platform: time
    hours: '/01'
    minutes: 00
    seconds: 00
  action:
    entity_id: switch._slot_3
    service_template: >
      {% if is_state("switch._slot_3", "off") and states.sensor.yweather_temperature.state|int < 22  %}
        switch.turn_on
      {%-elif is_state("switch._slot_3", "on") %}
        switch.turn_off
      {% endif %}


# 触发条件：每半个小时触发一次
# 动作:开或关
- id: 'Aquarium water circulation'
  alias: 鱼缸水循环slot
  trigger:
    platform: time
    minutes: /30
    seconds: 0
  action:
    entity_id: switch._slot
    service_template: >
      {% if is_state("switch._slot", "off") %}
        switch.turn_on
      {%-elif is_state("switch._slot", "on") %}
        switch.turn_off
      {% endif %}


