- platform: broadlink
  host: 192.168.1.123
  mac: '34:ea:34:c7:6a:d7'
  entity_namespace: holiday_house
  switches:
    tv:
      friendly_name: "客厅电视(TV)"
      command_on: "JgBQAAABJpMTEhMREhQRExETEhQROBITEBQSExETEhMSEhITETgRFRETETgTExE3ExMREhEVERQRNxMTETcTExA5EjcSOBE4FAAGAgABJUoSAA0FAAAAAAAAAAA="
      command_off: "JgBQAAABJpMTEhMREhQRExETEhQROBITEBQSExETEhMSEhITETgRFRETETgTExE3ExMREhEVERQRNxMTETcTExA5EjcSOBE4FAAGAgABJUoSAA0FAAAAAAAAAAA="
    ac:
      friendly_name: "客厅空调(AC)"
      command_on: "JgAkAQABIpQUFBIVFBMTNxUTExQSFRMUEzkSFBMVEzcUFBMTFBQTFBMVEhUTExQUEhUTNxQUFRMTFBMUExQSFRM3ExUSOBQTFRQSOBMUFAACjBQUExQTExQUExUSFBQUEhQUFBMUExUTExQTFDcWEhIVExQTFBMVEhUUExMUExQSFhMUEhUSFRMUEjgUFBQ2FDcVAAUYAAEjlBQUEhUTExQ3FBMUExQUExUSOBQUExQSOBUTEhQUExUTEhYSFBQUExQTFBM3FRMTFREWExMUFBMUEzcVNhU2FBMUFBQ2FBQTAAKMFRQSFRIUFBMUFBIVExUSFRIUFRMTExQUFBMTFRMUExQTFBIWEhUTFBMUExQTFBQUEhUTFBMUExQSOBQ3FRMUNhQADQUAAAAA"
      command_off: "JgAkAQABIpQUFBIVFBMTNxUTExQSFRMUEzkSFBMVEzcUFBMTFBQTFBMVEhUTExQUEhUTNxQUFRMTFBMUExQSFRM3ExUSOBQTFRQSOBMUFAACjBQUExQTExQUExUSFBQUEhQUFBMUExUTExQTFDcWEhIVExQTFBMVEhUUExMUExQSFhMUEhUSFRMUEjgUFBQ2FDcVAAUYAAEjlBQUEhUTExQ3FBMUExQUExUSOBQUExQSOBUTEhQUExUTEhYSFBQUExQTFBM3FRMTFREWExMUFBMUEzcVNhU2FBMUFBQ2FBQTAAKMFRQSFRIUFBMUFBIVExUSFRIUFRMTExQUFBMTFRMUExQTFBIWEhUTFBMUExQTFBQUEhUTFBMUExQSOBQ3FRMUNhQADQUAAAAA"
