- platform: broadlink
  host: 192.168.1.123
  mac: '34:ea:34:c7:6a:d7'
  entity_namespace: holiday_house
  switches:
    tv:
      friendly_name: "客厅电视(TV)"
      command_on: "JgBQAAABJpMTEhMREhQRExETEhQROBITEBQSExETEhMSEhITETgRFRETETgTExE3ExMREhEVERQRNxMTETcTExA5EjcSOBE4FAAGAgABJUoSAA0FAAAAAAAAAAA="
      command_off: "JgBQAAABJpMTEhMREhQRExETEhQROBITEBQSExETEhMSEhITETgRFRETETgTExE3ExMREhEVERQRNxMTETcTExA5EjcSOBE4FAAGAgABJUoSAA0FAAAAAAAAAAA="
    ac:
      friendly_name: "客厅空调(AC)"
      command_on: "JgAkAQABIpQUFBIVFBMTNxUTExQSFRMUEzkSFBMVEzcUFBMTFBQTFBMVEhUTExQUEhUTNxQUFRMTFBMUExQSFRM3ExUSOBQTFRQSOBMUFAACjBQUExQTExQUExUSFBQUEhQUFBMUExUTExQTFDcWEhIVExQTFBMVEhUUExMUExQSFhMUEhUSFRMUEjgUFBQ2FDcVAAUYAAEjlBQUEhUTExQ3FBMUExQUExUSOBQUExQSOBUTEhQUExUTEhYSFBQUExQTFBM3FRMTFREWExMUFBMUEzcVNhU2FBMUFBQ2FBQTAAKMFRQSFRIUFBMUFBIVExUSFRIUFRMTExQUFBMTFRMUExQTFBIWEhUTFBMUExQTFBQUEhUTFBMUExQSOBQ3FRMUNhQADQUAAAAA"
      command_off: "JgAkAQABIpQUFBIVFBMTNxUTExQSFRMUEzkSFBMVEzcUFBMTFBQTFBMVEhUTExQUEhUTNxQUFRMTFBMUExQSFRM3ExUSOBQTFRQSOBMUFAACjBQUExQTExQUExUSFBQUEhQUFBMUExUTExQTFDcWEhIVExQTFBMVEhUUExMUExQSFhMUEhUSFRMUEjgUFBQ2FDcVAAUYAAEjlBQUEhUTExQ3FBMUExQUExUSOBQUExQSOBUTEhQUExUTEhYSFBQUExQTFBM3FRMTFREWExMUFBMUEzcVNhU2FBMUFBQ2FBQTAAKMFRQSFRIUFBMUFBIVExUSFRIUFRMTExQUFBMTFRMUExQTFBIWEhUTFBMUExQTFBQUEhUTFBMUExQSOBQ3FRMUNhQADQUAAAAA"

- platform: broadlink
  host: 192.168.1.100
  mac: '34:EA:34:D1:03:34'
  type: mp1
  friendly_name: "插排1"
  slots:
    slot_1: 'slot1鱼缸灯'
    slot_2: 'slot2鱼缸水循环'
    slot_3: 'slot3鱼缸加热棒'
    slot_4: 'slot4其他'

- platform: wake_on_lan
  name: "MacBook WOL" 
  mac_address: "a4-5e-60-f2-9d-b3"
  host: "192.168.1.175"
  #  broadcast_address: "192.168.1.175"
  turn_off:
    service: shell_command.turn_off_macbook


